// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwc2bM5-TG4h4V-qbbERlrqwRo9eweP1M',
    appId: '1:699246740449:web:b79001139228b0401308a0',
    messagingSenderId: '699246740449',
    projectId: 't2med-9a1a5',
    authDomain: 't2med-9a1a5.firebaseapp.com',
    storageBucket: 't2med-9a1a5.firebasestorage.app',
    measurementId: 'G-8MJB0DE0CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_I4xmWKstjEhUYXqaEz5whBhU7Cp3SE',
    appId: '1:699246740449:android:333b783571d01dab1308a0',
    messagingSenderId: '699246740449',
    projectId: 't2med-9a1a5',
    storageBucket: 't2med-9a1a5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwc2bM5-TG4h4V-qbbERlrqwRo9eweP1M',
    appId: '1:699246740449:web:47e8f05656294ad81308a0',
    messagingSenderId: '699246740449',
    projectId: 't2med-9a1a5',
    authDomain: 't2med-9a1a5.firebaseapp.com',
    storageBucket: 't2med-9a1a5.firebasestorage.app',
    measurementId: 'G-Y7J6WB6CS9',
  );
}