// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BC_NWQkHgi1BAhfCrJg7mJaTz5wqFsY',
    appId: '1:356929768009:web:8e27940444967f9d3a0d98',
    messagingSenderId: '356929768009',
    projectId: 't2med-6e5de',
    authDomain: 't2med-6e5de.firebaseapp.com',
    storageBucket: 't2med-6e5de.firebasestorage.app',
    measurementId: 'G-7JP7YC6KHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2NqqFPlp4cWQ_j4d8ejcUObjrg1HvzE',
    appId: '1:356929768009:android:ffb84492305789603a0d98',
    messagingSenderId: '356929768009',
    projectId: 't2med-6e5de',
    storageBucket: 't2med-6e5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgHXPVCpagvtn1AlLjy_gN5NNtyK_FPw',
    appId: '1:356929768009:ios:9b59cde19553fde23a0d98',
    messagingSenderId: '356929768009',
    projectId: 't2med-6e5de',
    storageBucket: 't2med-6e5de.firebasestorage.app',
    iosBundleId: 'com.example.t2med',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgHXPVCpagvtn1AlLjy_gN5NNtyK_FPw',
    appId: '1:356929768009:ios:9b59cde19553fde23a0d98',
    messagingSenderId: '356929768009',
    projectId: 't2med-6e5de',
    storageBucket: 't2med-6e5de.firebasestorage.app',
    iosBundleId: 'com.example.t2med',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9BC_NWQkHgi1BAhfCrJg7mJaTz5wqFsY',
    appId: '1:356929768009:web:185d946c20fcba6e3a0d98',
    messagingSenderId: '356929768009',
    projectId: 't2med-6e5de',
    authDomain: 't2med-6e5de.firebaseapp.com',
    storageBucket: 't2med-6e5de.firebasestorage.app',
    measurementId: 'G-14YHLQPCJ0',
  );
}
